### ISSUE TITLE
This sample is not working throwing error System.ArgumentException: 'Invalid property or field'

### ISSUE THREAD

**Issue by JayendraYadav1982** [georgekosmidis/blog.georgekosmidis.net#189]
https://github.com/georgekosmidis/blog.georgekosmidis.net//tree/main/workables/articles/100140-asp-net-mvc-5-with-razor-kendo-ui-dynamic-grid-creation-columns-ordering-grouping-and-paging/content.html

**Comment by georgekosmidis** [comment]
Since this is an 8 year old sample I guess you are using a much newer version.
Which one?
Can you post more details?

**Comment by georgekosmidis** [comment]
Closing this issue because there is no response from the original author - feel free to reopen it.

**Comment by georgekosmidis** [comment]
Closing this issue because there is no response from the original author - feel free to reopen it.
