### ISSUE TITLE
Can IiteDb be used for Blazor PWA

### ISSUE THREAD

**Issue by aboah** [georgekosmidis/blog.georgekosmidis.net#3]
Hi Mr George Kosmidis,
I want to find out whether LiteDb can be used for blazor web assembly projects especially PWA

**Comment by georgekosmidis** [comment]
Hello @aboah,
I think you will find this helpful: https://blazorlitedb.herokuapp.com/

**Comment by georgekosmidis** [comment]
I am going to close this issue since there is no other response. Feel free to reopen it!
