### ISSUE TITLE
Unable to get this to work in ASP.NET Core Web API project using .NET 8.0

### ISSUE THREAD

**Issue by k7mck** [georgekosmidis/blog.georgekosmidis.net#646]
https://github.com/georgekosmidis/blog.georgekosmidis.net//tree/main/workables/articles/100260-using-litedb-in-an-asp-net-core-api/content.html

I cannot get this service to work in an ASP.NET Core Web API project using .NET 8.0.  The difference  - as far as I can tell - only exists in how Program.cs and Start.cs are setup.  Can you update/revise this project to use .NET 8.0?

**Comment by georgekosmidis** [comment]
Hello!
Thanks for reaching out for this!
Can you possible add the errors you are seeing?

**Comment by georgekosmidis** [comment]
I ll be closing this now, as there is no response, but feel free to reopen it!
